# Read the Docs : Reproducible builds
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Declare Python requirements
python:
  install:
  - requirements: docs/requirements.txt
