# Read the Docs : Reproducible builds
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

version: 2

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  version: 3.7
  install:
  - requirements: docs/requirements.txt
