// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: molecule.proto

package uk.ac.sussex.gdsc.smlm.data.config;

@SuppressWarnings({"unchecked", "unused", "javadoc", "static-method", "cast"})
public final class MoleculeProtos {
  private MoleculeProtos() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface AtomOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uk.ac.sussex.gdsc.smlm.data.config.Atom)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double mass = 1;</code>
     */
    double getMass();

    /**
     * <code>double x = 2;</code>
     */
    double getX();

    /**
     * <code>double y = 3;</code>
     */
    double getY();

    /**
     * <code>double z = 4;</code>
     */
    double getZ();
  }
  /**
   * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.Atom}
   */
  public static final class Atom extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uk.ac.sussex.gdsc.smlm.data.config.Atom)
      AtomOrBuilder {
    // Use Atom.newBuilder() to construct.
    private Atom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Atom() {
      mass_ = 0D;
      x_ = 0D;
      y_ = 0D;
      z_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Atom(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              mass_ = input.readDouble();
              break;
            }
            case 17: {

              x_ = input.readDouble();
              break;
            }
            case 25: {

              y_ = input.readDouble();
              break;
            }
            case 33: {

              z_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.class,
              uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder.class);
    }

    public static final int MASS_FIELD_NUMBER = 1;
    private double mass_;

    /**
     * <code>double mass = 1;</code>
     */
    public double getMass() {
      return mass_;
    }

    public static final int X_FIELD_NUMBER = 2;
    private double x_;

    /**
     * <code>double x = 2;</code>
     */
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private double y_;

    /**
     * <code>double y = 3;</code>
     */
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 4;
    private double z_;

    /**
     * <code>double z = 4;</code>
     */
    public double getZ() {
      return z_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (mass_ != 0D) {
        output.writeDouble(1, mass_);
      }
      if (x_ != 0D) {
        output.writeDouble(2, x_);
      }
      if (y_ != 0D) {
        output.writeDouble(3, y_);
      }
      if (z_ != 0D) {
        output.writeDouble(4, z_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (mass_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(1, mass_);
      }
      if (x_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, x_);
      }
      if (y_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(3, y_);
      }
      if (z_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(4, z_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom)) {
        return super.equals(obj);
      }
      uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom other =
          (uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom) obj;

      boolean result = true;
      result = result && (java.lang.Double.doubleToLongBits(getMass()) == java.lang.Double
          .doubleToLongBits(other.getMass()));
      result = result && (java.lang.Double.doubleToLongBits(getX()) == java.lang.Double
          .doubleToLongBits(other.getX()));
      result = result && (java.lang.Double.doubleToLongBits(getY()) == java.lang.Double
          .doubleToLongBits(other.getY()));
      result = result && (java.lang.Double.doubleToLongBits(getZ()) == java.lang.Double
          .doubleToLongBits(other.getZ()));
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MASS_FIELD_NUMBER;
      hash = (53 * hash)
          + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getMass()));
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash)
          + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash)
          + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash)
          + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getZ()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.Atom}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uk.ac.sussex.gdsc.smlm.data.config.Atom)
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.class,
                uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder.class);
      }

      // Construct using uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
        }
      }

      public Builder clear() {
        super.clear();
        mass_ = 0D;

        x_ = 0D;

        y_ = 0D;

        z_ = 0D;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_descriptor;
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom getDefaultInstanceForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.getDefaultInstance();
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom build() {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom buildPartial() {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom result =
            new uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom(this);
        result.mass_ = mass_;
        result.x_ = x_;
        result.y_ = y_;
        result.z_ = z_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom) {
          return mergeFrom((uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom other) {
        if (other == uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.getDefaultInstance())
          return this;
        if (other.getMass() != 0D) {
          setMass(other.getMass());
        }
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.getZ() != 0D) {
          setZ(other.getZ());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double mass_;

      /**
       * <code>double mass = 1;</code>
       */
      public double getMass() {
        return mass_;
      }

      /**
       * <code>double mass = 1;</code>
       */
      public Builder setMass(double value) {

        mass_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double mass = 1;</code>
       */
      public Builder clearMass() {

        mass_ = 0D;
        onChanged();
        return this;
      }

      private double x_;

      /**
       * <code>double x = 2;</code>
       */
      public double getX() {
        return x_;
      }

      /**
       * <code>double x = 2;</code>
       */
      public Builder setX(double value) {

        x_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double x = 2;</code>
       */
      public Builder clearX() {

        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_;

      /**
       * <code>double y = 3;</code>
       */
      public double getY() {
        return y_;
      }

      /**
       * <code>double y = 3;</code>
       */
      public Builder setY(double value) {

        y_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double y = 3;</code>
       */
      public Builder clearY() {

        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_;

      /**
       * <code>double z = 4;</code>
       */
      public double getZ() {
        return z_;
      }

      /**
       * <code>double z = 4;</code>
       */
      public Builder setZ(double value) {

        z_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double z = 4;</code>
       */
      public Builder clearZ() {

        z_ = 0D;
        onChanged();
        return this;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:uk.ac.sussex.gdsc.smlm.data.config.Atom)
    }

    // @@protoc_insertion_point(class_scope:uk.ac.sussex.gdsc.smlm.data.config.Atom)
    private static final uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom();
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Atom> PARSER =
        new com.google.protobuf.AbstractParser<Atom>() {
          public Atom parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Atom(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Atom> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Atom> getParserForType() {
      return PARSER;
    }

    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MoleculeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uk.ac.sussex.gdsc.smlm.data.config.Molecule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double fraction = 1;</code>
     */
    double getFraction();

    /**
     * <code>double diffusion_rate = 2;</code>
     */
    double getDiffusionRate();

    /**
     * <code>string diffusion_type = 3;</code>
     */
    java.lang.String getDiffusionType();

    /**
     * <code>string diffusion_type = 3;</code>
     */
    com.google.protobuf.ByteString getDiffusionTypeBytes();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom> getAtomList();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom getAtom(int index);

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    int getAtomCount();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    java.util.List<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder> getAtomOrBuilderList();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder getAtomOrBuilder(int index);
  }
  /**
   * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.Molecule}
   */
  public static final class Molecule extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uk.ac.sussex.gdsc.smlm.data.config.Molecule)
      MoleculeOrBuilder {
    // Use Molecule.newBuilder() to construct.
    private Molecule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Molecule() {
      fraction_ = 0D;
      diffusionRate_ = 0D;
      diffusionType_ = "";
      atom_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Molecule(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 9: {

              fraction_ = input.readDouble();
              break;
            }
            case 17: {

              diffusionRate_ = input.readDouble();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              diffusionType_ = s;
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                atom_ =
                    new java.util.ArrayList<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom>();
                mutable_bitField0_ |= 0x00000008;
              }
              atom_.add(
                  input.readMessage(uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.parser(),
                      extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          atom_ = java.util.Collections.unmodifiableList(atom_);
        }
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.class,
              uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder.class);
    }

    private int bitField0_;
    public static final int FRACTION_FIELD_NUMBER = 1;
    private double fraction_;

    /**
     * <code>double fraction = 1;</code>
     */
    public double getFraction() {
      return fraction_;
    }

    public static final int DIFFUSION_RATE_FIELD_NUMBER = 2;
    private double diffusionRate_;

    /**
     * <code>double diffusion_rate = 2;</code>
     */
    public double getDiffusionRate() {
      return diffusionRate_;
    }

    public static final int DIFFUSION_TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object diffusionType_;

    /**
     * <code>string diffusion_type = 3;</code>
     */
    public java.lang.String getDiffusionType() {
      java.lang.Object ref = diffusionType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        diffusionType_ = s;
        return s;
      }
    }

    /**
     * <code>string diffusion_type = 3;</code>
     */
    public com.google.protobuf.ByteString getDiffusionTypeBytes() {
      java.lang.Object ref = diffusionType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
        diffusionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ATOM_FIELD_NUMBER = 4;
    private java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom> atom_;

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    public java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom> getAtomList() {
      return atom_;
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    public java.util.List<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder> getAtomOrBuilderList() {
      return atom_;
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    public int getAtomCount() {
      return atom_.size();
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom getAtom(int index) {
      return atom_.get(index);
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
     */
    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder getAtomOrBuilder(
        int index) {
      return atom_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      if (fraction_ != 0D) {
        output.writeDouble(1, fraction_);
      }
      if (diffusionRate_ != 0D) {
        output.writeDouble(2, diffusionRate_);
      }
      if (!getDiffusionTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, diffusionType_);
      }
      for (int i = 0; i < atom_.size(); i++) {
        output.writeMessage(4, atom_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      if (fraction_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(1, fraction_);
      }
      if (diffusionRate_ != 0D) {
        size += com.google.protobuf.CodedOutputStream.computeDoubleSize(2, diffusionRate_);
      }
      if (!getDiffusionTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, diffusionType_);
      }
      for (int i = 0; i < atom_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(4, atom_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule)) {
        return super.equals(obj);
      }
      uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule other =
          (uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule) obj;

      boolean result = true;
      result = result && (java.lang.Double.doubleToLongBits(getFraction()) == java.lang.Double
          .doubleToLongBits(other.getFraction()));
      result = result && (java.lang.Double.doubleToLongBits(getDiffusionRate()) == java.lang.Double
          .doubleToLongBits(other.getDiffusionRate()));
      result = result && getDiffusionType().equals(other.getDiffusionType());
      result = result && getAtomList().equals(other.getAtomList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FRACTION_FIELD_NUMBER;
      hash = (53 * hash)
          + com.google.protobuf.Internal.hashLong(java.lang.Double.doubleToLongBits(getFraction()));
      hash = (37 * hash) + DIFFUSION_RATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal
          .hashLong(java.lang.Double.doubleToLongBits(getDiffusionRate()));
      hash = (37 * hash) + DIFFUSION_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getDiffusionType().hashCode();
      if (getAtomCount() > 0) {
        hash = (37 * hash) + ATOM_FIELD_NUMBER;
        hash = (53 * hash) + getAtomList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.Molecule}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uk.ac.sussex.gdsc.smlm.data.config.Molecule)
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.class,
                uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder.class);
      }

      // Construct using uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getAtomFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        fraction_ = 0D;

        diffusionRate_ = 0D;

        diffusionType_ = "";

        if (atomBuilder_ == null) {
          atom_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          atomBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_descriptor;
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule getDefaultInstanceForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.getDefaultInstance();
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule build() {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule buildPartial() {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule result =
            new uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.fraction_ = fraction_;
        result.diffusionRate_ = diffusionRate_;
        result.diffusionType_ = diffusionType_;
        if (atomBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            atom_ = java.util.Collections.unmodifiableList(atom_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.atom_ = atom_;
        } else {
          result.atom_ = atomBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule) {
          return mergeFrom((uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule other) {
        if (other == uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule
            .getDefaultInstance())
          return this;
        if (other.getFraction() != 0D) {
          setFraction(other.getFraction());
        }
        if (other.getDiffusionRate() != 0D) {
          setDiffusionRate(other.getDiffusionRate());
        }
        if (!other.getDiffusionType().isEmpty()) {
          diffusionType_ = other.diffusionType_;
          onChanged();
        }
        if (atomBuilder_ == null) {
          if (!other.atom_.isEmpty()) {
            if (atom_.isEmpty()) {
              atom_ = other.atom_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureAtomIsMutable();
              atom_.addAll(other.atom_);
            }
            onChanged();
          }
        } else {
          if (!other.atom_.isEmpty()) {
            if (atomBuilder_.isEmpty()) {
              atomBuilder_.dispose();
              atomBuilder_ = null;
              atom_ = other.atom_;
              bitField0_ = (bitField0_ & ~0x00000008);
              atomBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                  ? getAtomFieldBuilder()
                  : null;
            } else {
              atomBuilder_.addAllMessages(other.atom_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private double fraction_;

      /**
       * <code>double fraction = 1;</code>
       */
      public double getFraction() {
        return fraction_;
      }

      /**
       * <code>double fraction = 1;</code>
       */
      public Builder setFraction(double value) {

        fraction_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double fraction = 1;</code>
       */
      public Builder clearFraction() {

        fraction_ = 0D;
        onChanged();
        return this;
      }

      private double diffusionRate_;

      /**
       * <code>double diffusion_rate = 2;</code>
       */
      public double getDiffusionRate() {
        return diffusionRate_;
      }

      /**
       * <code>double diffusion_rate = 2;</code>
       */
      public Builder setDiffusionRate(double value) {

        diffusionRate_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>double diffusion_rate = 2;</code>
       */
      public Builder clearDiffusionRate() {

        diffusionRate_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object diffusionType_ = "";

      /**
       * <code>string diffusion_type = 3;</code>
       */
      public java.lang.String getDiffusionType() {
        java.lang.Object ref = diffusionType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          diffusionType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }

      /**
       * <code>string diffusion_type = 3;</code>
       */
      public com.google.protobuf.ByteString getDiffusionTypeBytes() {
        java.lang.Object ref = diffusionType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          diffusionType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      /**
       * <code>string diffusion_type = 3;</code>
       */
      public Builder setDiffusionType(java.lang.String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        diffusionType_ = value;
        onChanged();
        return this;
      }

      /**
       * <code>string diffusion_type = 3;</code>
       */
      public Builder clearDiffusionType() {

        diffusionType_ = getDefaultInstance().getDiffusionType();
        onChanged();
        return this;
      }

      /**
       * <code>string diffusion_type = 3;</code>
       */
      public Builder setDiffusionTypeBytes(com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        diffusionType_ = value;
        onChanged();
        return this;
      }

      private java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom> atom_ =
          java.util.Collections.emptyList();

      private void ensureAtomIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          atom_ = new java.util.ArrayList<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom>(
              atom_);
          bitField0_ |= 0x00000008;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder> atomBuilder_;

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom> getAtomList() {
        if (atomBuilder_ == null) {
          return java.util.Collections.unmodifiableList(atom_);
        } else {
          return atomBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public int getAtomCount() {
        if (atomBuilder_ == null) {
          return atom_.size();
        } else {
          return atomBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom getAtom(int index) {
        if (atomBuilder_ == null) {
          return atom_.get(index);
        } else {
          return atomBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder setAtom(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom value) {
        if (atomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtomIsMutable();
          atom_.set(index, value);
          onChanged();
        } else {
          atomBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder setAtom(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder builderForValue) {
        if (atomBuilder_ == null) {
          ensureAtomIsMutable();
          atom_.set(index, builderForValue.build());
          onChanged();
        } else {
          atomBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder addAtom(uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom value) {
        if (atomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtomIsMutable();
          atom_.add(value);
          onChanged();
        } else {
          atomBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder addAtom(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom value) {
        if (atomBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAtomIsMutable();
          atom_.add(index, value);
          onChanged();
        } else {
          atomBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder addAtom(
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder builderForValue) {
        if (atomBuilder_ == null) {
          ensureAtomIsMutable();
          atom_.add(builderForValue.build());
          onChanged();
        } else {
          atomBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder addAtom(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder builderForValue) {
        if (atomBuilder_ == null) {
          ensureAtomIsMutable();
          atom_.add(index, builderForValue.build());
          onChanged();
        } else {
          atomBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder addAllAtom(
          java.lang.Iterable<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom> values) {
        if (atomBuilder_ == null) {
          ensureAtomIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, atom_);
          onChanged();
        } else {
          atomBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder clearAtom() {
        if (atomBuilder_ == null) {
          atom_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          atomBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public Builder removeAtom(int index) {
        if (atomBuilder_ == null) {
          ensureAtomIsMutable();
          atom_.remove(index);
          onChanged();
        } else {
          atomBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder getAtomBuilder(
          int index) {
        return getAtomFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder getAtomOrBuilder(
          int index) {
        if (atomBuilder_ == null) {
          return atom_.get(index);
        } else {
          return atomBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public java.util.List<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder> getAtomOrBuilderList() {
        if (atomBuilder_ != null) {
          return atomBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(atom_);
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder addAtomBuilder() {
        return getAtomFieldBuilder().addBuilder(
            uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.getDefaultInstance());
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder addAtomBuilder(
          int index) {
        return getAtomFieldBuilder().addBuilder(index,
            uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.getDefaultInstance());
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Atom atom = 4;</code>
       */
      public java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder> getAtomBuilderList() {
        return getAtomFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder> getAtomFieldBuilder() {
        if (atomBuilder_ == null) {
          atomBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Atom.Builder, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.AtomOrBuilder>(
                  atom_, ((bitField0_ & 0x00000008) == 0x00000008), getParentForChildren(),
                  isClean());
          atom_ = null;
        }
        return atomBuilder_;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:uk.ac.sussex.gdsc.smlm.data.config.Molecule)
    }

    // @@protoc_insertion_point(class_scope:uk.ac.sussex.gdsc.smlm.data.config.Molecule)
    private static final uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule();
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Molecule> PARSER =
        new com.google.protobuf.AbstractParser<Molecule>() {
          public Molecule parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Molecule(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Molecule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Molecule> getParserForType() {
      return PARSER;
    }

    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MixtureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uk.ac.sussex.gdsc.smlm.data.config.Mixture)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule> getMoleculeList();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule getMolecule(int index);

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    int getMoleculeCount();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    java.util.List<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder> getMoleculeOrBuilderList();

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder getMoleculeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.Mixture}
   */
  public static final class Mixture extends com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uk.ac.sussex.gdsc.smlm.data.config.Mixture)
      MixtureOrBuilder {
    // Use Mixture.newBuilder() to construct.
    private Mixture(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private Mixture() {
      molecule_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private Mixture(com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                molecule_ =
                    new java.util.ArrayList<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule>();
                mutable_bitField0_ |= 0x00000001;
              }
              molecule_.add(input.readMessage(
                  uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.parser(),
                  extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          molecule_ = java.util.Collections.unmodifiableList(molecule_);
        }
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
      return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.class,
              uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.Builder.class);
    }

    public static final int MOLECULE_FIELD_NUMBER = 1;
    private java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule> molecule_;

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    public java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule> getMoleculeList() {
      return molecule_;
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    public java.util.List<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder> getMoleculeOrBuilderList() {
      return molecule_;
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    public int getMoleculeCount() {
      return molecule_.size();
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule getMolecule(int index) {
      return molecule_.get(index);
    }

    /**
     * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
     */
    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder getMoleculeOrBuilder(
        int index) {
      return molecule_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1)
        return true;
      if (isInitialized == 0)
        return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      for (int i = 0; i < molecule_.size(); i++) {
        output.writeMessage(1, molecule_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1)
        return size;

      size = 0;
      for (int i = 0; i < molecule_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, molecule_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture)) {
        return super.equals(obj);
      }
      uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture other =
          (uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture) obj;

      boolean result = true;
      result = result && getMoleculeList().equals(other.getMoleculeList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMoleculeCount() > 0) {
        hash = (37 * hash) + MOLECULE_FIELD_NUMBER;
        hash = (53 * hash) + getMoleculeList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input,
          extensionRegistry);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input,
          extensionRegistry);
    }

    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.Mixture}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uk.ac.sussex.gdsc.smlm.data.config.Mixture)
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MixtureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.class,
                uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.Builder.class);
      }

      // Construct using uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getMoleculeFieldBuilder();
        }
      }

      public Builder clear() {
        super.clear();
        if (moleculeBuilder_ == null) {
          molecule_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          moleculeBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_descriptor;
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture getDefaultInstanceForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.getDefaultInstance();
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture build() {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture buildPartial() {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture result =
            new uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture(this);
        int from_bitField0_ = bitField0_;
        if (moleculeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            molecule_ = java.util.Collections.unmodifiableList(molecule_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.molecule_ = molecule_;
        } else {
          result.molecule_ = moleculeBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }

      public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
        return (Builder) super.setField(field, value);
      }

      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }

      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }

      public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }

      public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture) {
          return mergeFrom((uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture other) {
        if (other == uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture.getDefaultInstance())
          return this;
        if (moleculeBuilder_ == null) {
          if (!other.molecule_.isEmpty()) {
            if (molecule_.isEmpty()) {
              molecule_ = other.molecule_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMoleculeIsMutable();
              molecule_.addAll(other.molecule_);
            }
            onChanged();
          }
        } else {
          if (!other.molecule_.isEmpty()) {
            if (moleculeBuilder_.isEmpty()) {
              moleculeBuilder_.dispose();
              moleculeBuilder_ = null;
              molecule_ = other.molecule_;
              bitField0_ = (bitField0_ & ~0x00000001);
              moleculeBuilder_ = com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                  ? getMoleculeFieldBuilder()
                  : null;
            } else {
              moleculeBuilder_.addAllMessages(other.molecule_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule> molecule_ =
          java.util.Collections.emptyList();

      private void ensureMoleculeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          molecule_ =
              new java.util.ArrayList<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule>(
                  molecule_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder> moleculeBuilder_;

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule> getMoleculeList() {
        if (moleculeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(molecule_);
        } else {
          return moleculeBuilder_.getMessageList();
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public int getMoleculeCount() {
        if (moleculeBuilder_ == null) {
          return molecule_.size();
        } else {
          return moleculeBuilder_.getCount();
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule getMolecule(int index) {
        if (moleculeBuilder_ == null) {
          return molecule_.get(index);
        } else {
          return moleculeBuilder_.getMessage(index);
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder setMolecule(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule value) {
        if (moleculeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoleculeIsMutable();
          molecule_.set(index, value);
          onChanged();
        } else {
          moleculeBuilder_.setMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder setMolecule(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder builderForValue) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.set(index, builderForValue.build());
          onChanged();
        } else {
          moleculeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule value) {
        if (moleculeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoleculeIsMutable();
          molecule_.add(value);
          onChanged();
        } else {
          moleculeBuilder_.addMessage(value);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule value) {
        if (moleculeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoleculeIsMutable();
          molecule_.add(index, value);
          onChanged();
        } else {
          moleculeBuilder_.addMessage(index, value);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder builderForValue) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.add(builderForValue.build());
          onChanged();
        } else {
          moleculeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder addMolecule(int index,
          uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder builderForValue) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.add(index, builderForValue.build());
          onChanged();
        } else {
          moleculeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder addAllMolecule(
          java.lang.Iterable<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule> values) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, molecule_);
          onChanged();
        } else {
          moleculeBuilder_.addAllMessages(values);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder clearMolecule() {
        if (moleculeBuilder_ == null) {
          molecule_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          moleculeBuilder_.clear();
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public Builder removeMolecule(int index) {
        if (moleculeBuilder_ == null) {
          ensureMoleculeIsMutable();
          molecule_.remove(index);
          onChanged();
        } else {
          moleculeBuilder_.remove(index);
        }
        return this;
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder getMoleculeBuilder(
          int index) {
        return getMoleculeFieldBuilder().getBuilder(index);
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder getMoleculeOrBuilder(
          int index) {
        if (moleculeBuilder_ == null) {
          return molecule_.get(index);
        } else {
          return moleculeBuilder_.getMessageOrBuilder(index);
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public java.util.List<? extends uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder> getMoleculeOrBuilderList() {
        if (moleculeBuilder_ != null) {
          return moleculeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(molecule_);
        }
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder addMoleculeBuilder() {
        return getMoleculeFieldBuilder().addBuilder(
            uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.getDefaultInstance());
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder addMoleculeBuilder(
          int index) {
        return getMoleculeFieldBuilder().addBuilder(index,
            uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.getDefaultInstance());
      }

      /**
       * <code>repeated .uk.ac.sussex.gdsc.smlm.data.config.Molecule molecule = 1;</code>
       */
      public java.util.List<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder> getMoleculeBuilderList() {
        return getMoleculeFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder> getMoleculeFieldBuilder() {
        if (moleculeBuilder_ == null) {
          moleculeBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Molecule.Builder, uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.MoleculeOrBuilder>(
                  molecule_, ((bitField0_ & 0x00000001) == 0x00000001), getParentForChildren(),
                  isClean());
          molecule_ = null;
        }
        return moleculeBuilder_;
      }

      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:uk.ac.sussex.gdsc.smlm.data.config.Mixture)
    }

    // @@protoc_insertion_point(class_scope:uk.ac.sussex.gdsc.smlm.data.config.Mixture)
    private static final uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture();
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Mixture> PARSER =
        new com.google.protobuf.AbstractParser<Mixture>() {
          public Mixture parsePartialFrom(com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new Mixture(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<Mixture> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Mixture> getParserForType() {
      return PARSER;
    }

    public uk.ac.sussex.gdsc.smlm.data.config.MoleculeProtos.Mixture getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {"\n\016molecule.proto\022\"uk.ac.sussex.gdsc.smlm"
        + ".data.config\"5\n\004Atom\022\014\n\004mass\030\001 \001(\001\022\t\n\001x\030"
        + "\002 \001(\001\022\t\n\001y\030\003 \001(\001\022\t\n\001z\030\004 \001(\001\"\204\001\n\010Molecule"
        + "\022\020\n\010fraction\030\001 \001(\001\022\026\n\016diffusion_rate\030\002 \001"
        + "(\001\022\026\n\016diffusion_type\030\003 \001(\t\0226\n\004atom\030\004 \003(\013"
        + "2(.uk.ac.sussex.gdsc.smlm.data.config.At"
        + "om\"I\n\007Mixture\022>\n\010molecule\030\001 \003(\0132,.uk.ac."
        + "sussex.gdsc.smlm.data.config.MoleculeB\020B" + "\016MoleculeProtosb\006proto3"};
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {}, assigner);
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_uk_ac_sussex_gdsc_smlm_data_config_Atom_descriptor,
            new java.lang.String[] {"Mass", "X", "Y", "Z",});
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_uk_ac_sussex_gdsc_smlm_data_config_Molecule_descriptor,
            new java.lang.String[] {"Fraction", "DiffusionRate", "DiffusionType", "Atom",});
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_uk_ac_sussex_gdsc_smlm_data_config_Mixture_descriptor,
            new java.lang.String[] {"Molecule",});
  }

  // @@protoc_insertion_point(outer_class_scope)
}
