// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template.proto

package uk.ac.sussex.gdsc.smlm.data.config;

@SuppressWarnings({"unchecked", "unused", "javadoc", "static-method", "cast"})
public final class TemplateProtos {
  private TemplateProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TemplateSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    java.util.List<java.lang.String>
        getNotesList();
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    int getNotesCount();
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    java.lang.String getNotes(int index);
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    com.google.protobuf.ByteString
        getNotesBytes(int index);

    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    boolean hasCalibration();
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration getCalibration();
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.CalibrationOrBuilder getCalibrationOrBuilder();

    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    boolean hasFitEngineSettings();
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings getFitEngineSettings();
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettingsOrBuilder getFitEngineSettingsOrBuilder();

    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    boolean hasResultsSettings();
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings getResultsSettings();
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettingsOrBuilder getResultsSettingsOrBuilder();

    /**
     * <pre>
     * The Point Spread Function (PSF)
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
     */
    boolean hasPsf();
    /**
     * <pre>
     * The Point Spread Function (PSF)
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF getPsf();
    /**
     * <pre>
     * The Point Spread Function (PSF)
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
     */
    uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSFOrBuilder getPsfOrBuilder();
  }
  /**
   * <pre>
   * Define the settings for the template.
   * </pre>
   *
   * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings}
   */
  public  static final class TemplateSettings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings)
      TemplateSettingsOrBuilder {
    // Use TemplateSettings.newBuilder() to construct.
    private TemplateSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TemplateSettings() {
      notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TemplateSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          final int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag))
				done = true;
              break;
            }
            case 10: {
              final java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                notes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              notes_.add(s);
              break;
            }
            case 18: {
              uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.Builder subBuilder = null;
              if (calibration_ != null)
				subBuilder = calibration_.toBuilder();
              calibration_ = input.readMessage(uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(calibration_);
                calibration_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.Builder subBuilder = null;
              if (fitEngineSettings_ != null)
				subBuilder = fitEngineSettings_.toBuilder();
              fitEngineSettings_ = input.readMessage(uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fitEngineSettings_);
                fitEngineSettings_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.Builder subBuilder = null;
              if (resultsSettings_ != null)
				subBuilder = resultsSettings_.toBuilder();
              resultsSettings_ = input.readMessage(uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultsSettings_);
                resultsSettings_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.Builder subBuilder = null;
              if (psf_ != null)
				subBuilder = psf_.toBuilder();
              psf_ = input.readMessage(uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(psf_);
                psf_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (final java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001))
			notes_ = notes_.getUnmodifiableView();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.class, uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.Builder.class);
    }

    private int bitField0_;
    public static final int NOTES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList notes_;
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    @Override
	public com.google.protobuf.ProtocolStringList
        getNotesList() {
      return notes_;
    }
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    @Override
	public int getNotesCount() {
      return notes_.size();
    }
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    @Override
	public java.lang.String getNotes(int index) {
      return notes_.get(index);
    }
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    @Override
	public com.google.protobuf.ByteString
        getNotesBytes(int index) {
      return notes_.getByteString(index);
    }

    public static final int CALIBRATION_FIELD_NUMBER = 2;
    private uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration calibration_;
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    @Override
	public boolean hasCalibration() {
      return calibration_ != null;
    }
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration getCalibration() {
      return calibration_ == null ? uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.getDefaultInstance() : calibration_;
    }
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.CalibrationOrBuilder getCalibrationOrBuilder() {
      return getCalibration();
    }

    public static final int FIT_ENGINE_SETTINGS_FIELD_NUMBER = 3;
    private uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings fitEngineSettings_;
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    @Override
	public boolean hasFitEngineSettings() {
      return fitEngineSettings_ != null;
    }
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings getFitEngineSettings() {
      return fitEngineSettings_ == null ? uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.getDefaultInstance() : fitEngineSettings_;
    }
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettingsOrBuilder getFitEngineSettingsOrBuilder() {
      return getFitEngineSettings();
    }

    public static final int RESULTS_SETTINGS_FIELD_NUMBER = 4;
    private uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings resultsSettings_;
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    @Override
	public boolean hasResultsSettings() {
      return resultsSettings_ != null;
    }
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings getResultsSettings() {
      return resultsSettings_ == null ? uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.getDefaultInstance() : resultsSettings_;
    }
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettingsOrBuilder getResultsSettingsOrBuilder() {
      return getResultsSettings();
    }

    public static final int PSF_FIELD_NUMBER = 5;
    private uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF psf_;
    /**
     * <pre>
     * The Point Spread Function (PSF)
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
     */
    @Override
	public boolean hasPsf() {
      return psf_ != null;
    }
    /**
     * <pre>
     * The Point Spread Function (PSF)
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF getPsf() {
      return psf_ == null ? uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.getDefaultInstance() : psf_;
    }
    /**
     * <pre>
     * The Point Spread Function (PSF)
     * </pre>
     *
     * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
     */
    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSFOrBuilder getPsfOrBuilder() {
      return getPsf();
    }

    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      final byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < notes_.size(); i++)
		com.google.protobuf.GeneratedMessageV3.writeString(output, 1, notes_.getRaw(i));
      if (calibration_ != null)
		output.writeMessage(2, getCalibration());
      if (fitEngineSettings_ != null)
		output.writeMessage(3, getFitEngineSettings());
      if (resultsSettings_ != null)
		output.writeMessage(4, getResultsSettings());
      if (psf_ != null)
		output.writeMessage(5, getPsf());
    }

    @Override
	public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < notes_.size(); i++)
			dataSize += computeStringSizeNoTag(notes_.getRaw(i));
        size += dataSize;
        size += 1 * getNotesList().size();
      }
      if (calibration_ != null)
		size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCalibration());
      if (fitEngineSettings_ != null)
		size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFitEngineSettings());
      if (resultsSettings_ != null)
		size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getResultsSettings());
      if (psf_ != null)
		size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getPsf());
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this)
		return true;
      if (!(obj instanceof uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings))
		return super.equals(obj);
      final uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings other = (uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings) obj;

      boolean result = true;
      result = result && getNotesList()
          .equals(other.getNotesList());
      result = result && (hasCalibration() == other.hasCalibration());
      if (hasCalibration())
		result = result && getCalibration()
            .equals(other.getCalibration());
      result = result && (hasFitEngineSettings() == other.hasFitEngineSettings());
      if (hasFitEngineSettings())
		result = result && getFitEngineSettings()
            .equals(other.getFitEngineSettings());
      result = result && (hasResultsSettings() == other.hasResultsSettings());
      if (hasResultsSettings())
		result = result && getResultsSettings()
            .equals(other.getResultsSettings());
      result = result && (hasPsf() == other.hasPsf());
      if (hasPsf())
		result = result && getPsf()
            .equals(other.getPsf());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0)
		return memoizedHashCode;
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNotesCount() > 0) {
        hash = (37 * hash) + NOTES_FIELD_NUMBER;
        hash = (53 * hash) + getNotesList().hashCode();
      }
      if (hasCalibration()) {
        hash = (37 * hash) + CALIBRATION_FIELD_NUMBER;
        hash = (53 * hash) + getCalibration().hashCode();
      }
      if (hasFitEngineSettings()) {
        hash = (37 * hash) + FIT_ENGINE_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getFitEngineSettings().hashCode();
      }
      if (hasResultsSettings()) {
        hash = (37 * hash) + RESULTS_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsSettings().hashCode();
      }
      if (hasPsf()) {
        hash = (37 * hash) + PSF_FIELD_NUMBER;
        hash = (53 * hash) + getPsf().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      final Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the settings for the template.
     * </pre>
     *
     * Protobuf type {@code uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings)
        uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.class, uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.Builder.class);
      }

      // Construct using uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
	public Builder clear() {
        super.clear();
        notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (calibrationBuilder_ == null)
			calibration_ = null;
		else {
          calibration_ = null;
          calibrationBuilder_ = null;
        }
        if (fitEngineSettingsBuilder_ == null)
			fitEngineSettings_ = null;
		else {
          fitEngineSettings_ = null;
          fitEngineSettingsBuilder_ = null;
        }
        if (resultsSettingsBuilder_ == null)
			resultsSettings_ = null;
		else {
          resultsSettings_ = null;
          resultsSettingsBuilder_ = null;
        }
        if (psfBuilder_ == null)
			psf_ = null;
		else {
          psf_ = null;
          psfBuilder_ = null;
        }
        return this;
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_descriptor;
      }

      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings getDefaultInstanceForType() {
        return uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.getDefaultInstance();
      }

      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings build() {
        final uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings result = buildPartial();
        if (!result.isInitialized())
			throw newUninitializedMessageException(result);
        return result;
      }

      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings buildPartial() {
        final uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings result = new uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings(this);
        final int from_bitField0_ = bitField0_;
        final int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = notes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.notes_ = notes_;
        if (calibrationBuilder_ == null)
			result.calibration_ = calibration_;
		else
			result.calibration_ = calibrationBuilder_.build();
        if (fitEngineSettingsBuilder_ == null)
			result.fitEngineSettings_ = fitEngineSettings_;
		else
			result.fitEngineSettings_ = fitEngineSettingsBuilder_.build();
        if (resultsSettingsBuilder_ == null)
			result.resultsSettings_ = resultsSettings_;
		else
			result.resultsSettings_ = resultsSettingsBuilder_.build();
        if (psfBuilder_ == null)
			result.psf_ = psf_;
		else
			result.psf_ = psfBuilder_.build();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
	public Builder clone() {
        return super.clone();
      }
      @Override
	public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
	public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
	public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
	public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
	public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings)
			return mergeFrom((uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings)other);
		else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings other) {
        if (other == uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings.getDefaultInstance()) return this;
        if (!other.notes_.isEmpty()) {
          if (notes_.isEmpty()) {
            notes_ = other.notes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNotesIsMutable();
            notes_.addAll(other.notes_);
          }
          onChanged();
        }
        if (other.hasCalibration())
			mergeCalibration(other.getCalibration());
        if (other.hasFitEngineSettings())
			mergeFitEngineSettings(other.getFitEngineSettings());
        if (other.hasResultsSettings())
			mergeResultsSettings(other.getResultsSettings());
        if (other.hasPsf())
			mergePsf(other.getPsf());
        onChanged();
        return this;
      }

      @Override
	public final boolean isInitialized() {
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null)
			mergeFrom(parsedMessage);
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNotesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = new com.google.protobuf.LazyStringArrayList(notes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      @Override
	public com.google.protobuf.ProtocolStringList
          getNotesList() {
        return notes_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      @Override
	public int getNotesCount() {
        return notes_.size();
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      @Override
	public java.lang.String getNotes(int index) {
        return notes_.get(index);
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      @Override
	public com.google.protobuf.ByteString
          getNotesBytes(int index) {
        return notes_.getByteString(index);
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder setNotes(
          int index, java.lang.String value) {
        if (value == null)
			throw new NullPointerException();
  ensureNotesIsMutable();
        notes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder addNotes(
          java.lang.String value) {
        if (value == null)
			throw new NullPointerException();
  ensureNotesIsMutable();
        notes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder addAllNotes(
          java.lang.Iterable<java.lang.String> values) {
        ensureNotesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, notes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder clearNotes() {
        notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder addNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null)
			throw new NullPointerException();
  checkByteStringIsUtf8(value);
        ensureNotesIsMutable();
        notes_.add(value);
        onChanged();
        return this;
      }

      private uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration calibration_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration, uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.Builder, uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.CalibrationOrBuilder> calibrationBuilder_;
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      @Override
	public boolean hasCalibration() {
        return calibrationBuilder_ != null || calibration_ != null;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration getCalibration() {
        if (calibrationBuilder_ == null)
			return calibration_ == null ? uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.getDefaultInstance() : calibration_;
		else
			return calibrationBuilder_.getMessage();
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder setCalibration(uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration value) {
        if (calibrationBuilder_ == null) {
          if (value == null)
			throw new NullPointerException();
          calibration_ = value;
          onChanged();
        }
		else
			calibrationBuilder_.setMessage(value);

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder setCalibration(
          uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.Builder builderForValue) {
        if (calibrationBuilder_ == null) {
          calibration_ = builderForValue.build();
          onChanged();
        }
		else
			calibrationBuilder_.setMessage(builderForValue.build());

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder mergeCalibration(uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration value) {
        if (calibrationBuilder_ == null) {
          if (calibration_ != null)
			calibration_ =
              uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.newBuilder(calibration_).mergeFrom(value).buildPartial();
		else
			calibration_ = value;
          onChanged();
        }
		else
			calibrationBuilder_.mergeFrom(value);

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder clearCalibration() {
        if (calibrationBuilder_ == null) {
          calibration_ = null;
          onChanged();
        } else {
          calibration_ = null;
          calibrationBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.Builder getCalibrationBuilder() {

        onChanged();
        return getCalibrationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.CalibrationOrBuilder getCalibrationOrBuilder() {
        if (calibrationBuilder_ != null)
			return calibrationBuilder_.getMessageOrBuilder();
		else
			return calibration_ == null ?
			      uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.getDefaultInstance() : calibration_;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration, uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.Calibration.Builder, uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.CalibrationOrBuilder>
          getCalibrationFieldBuilder() {
        if (calibrationBuilder_ == null) {
          calibrationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
                  getCalibration(),
                  getParentForChildren(),
                  isClean());
          calibration_ = null;
        }
        return calibrationBuilder_;
      }

      private uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings fitEngineSettings_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings, uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.Builder, uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettingsOrBuilder> fitEngineSettingsBuilder_;
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      @Override
	public boolean hasFitEngineSettings() {
        return fitEngineSettingsBuilder_ != null || fitEngineSettings_ != null;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings getFitEngineSettings() {
        if (fitEngineSettingsBuilder_ == null)
			return fitEngineSettings_ == null ? uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.getDefaultInstance() : fitEngineSettings_;
		else
			return fitEngineSettingsBuilder_.getMessage();
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder setFitEngineSettings(uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings value) {
        if (fitEngineSettingsBuilder_ == null) {
          if (value == null)
			throw new NullPointerException();
          fitEngineSettings_ = value;
          onChanged();
        }
		else
			fitEngineSettingsBuilder_.setMessage(value);

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder setFitEngineSettings(
          uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.Builder builderForValue) {
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettings_ = builderForValue.build();
          onChanged();
        }
		else
			fitEngineSettingsBuilder_.setMessage(builderForValue.build());

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder mergeFitEngineSettings(uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings value) {
        if (fitEngineSettingsBuilder_ == null) {
          if (fitEngineSettings_ != null)
			fitEngineSettings_ =
              uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.newBuilder(fitEngineSettings_).mergeFrom(value).buildPartial();
		else
			fitEngineSettings_ = value;
          onChanged();
        }
		else
			fitEngineSettingsBuilder_.mergeFrom(value);

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder clearFitEngineSettings() {
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettings_ = null;
          onChanged();
        } else {
          fitEngineSettings_ = null;
          fitEngineSettingsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.Builder getFitEngineSettingsBuilder() {

        onChanged();
        return getFitEngineSettingsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettingsOrBuilder getFitEngineSettingsOrBuilder() {
        if (fitEngineSettingsBuilder_ != null)
			return fitEngineSettingsBuilder_.getMessageOrBuilder();
		else
			return fitEngineSettings_ == null ?
			      uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.getDefaultInstance() : fitEngineSettings_;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings, uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettings.Builder, uk.ac.sussex.gdsc.smlm.data.config.FitProtos.FitEngineSettingsOrBuilder>
          getFitEngineSettingsFieldBuilder() {
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
                  getFitEngineSettings(),
                  getParentForChildren(),
                  isClean());
          fitEngineSettings_ = null;
        }
        return fitEngineSettingsBuilder_;
      }

      private uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings resultsSettings_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings, uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.Builder, uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettingsOrBuilder> resultsSettingsBuilder_;
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      @Override
	public boolean hasResultsSettings() {
        return resultsSettingsBuilder_ != null || resultsSettings_ != null;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings getResultsSettings() {
        if (resultsSettingsBuilder_ == null)
			return resultsSettings_ == null ? uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.getDefaultInstance() : resultsSettings_;
		else
			return resultsSettingsBuilder_.getMessage();
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder setResultsSettings(uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings value) {
        if (resultsSettingsBuilder_ == null) {
          if (value == null)
			throw new NullPointerException();
          resultsSettings_ = value;
          onChanged();
        }
		else
			resultsSettingsBuilder_.setMessage(value);

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder setResultsSettings(
          uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.Builder builderForValue) {
        if (resultsSettingsBuilder_ == null) {
          resultsSettings_ = builderForValue.build();
          onChanged();
        }
		else
			resultsSettingsBuilder_.setMessage(builderForValue.build());

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder mergeResultsSettings(uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings value) {
        if (resultsSettingsBuilder_ == null) {
          if (resultsSettings_ != null)
			resultsSettings_ =
              uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.newBuilder(resultsSettings_).mergeFrom(value).buildPartial();
		else
			resultsSettings_ = value;
          onChanged();
        }
		else
			resultsSettingsBuilder_.mergeFrom(value);

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder clearResultsSettings() {
        if (resultsSettingsBuilder_ == null) {
          resultsSettings_ = null;
          onChanged();
        } else {
          resultsSettings_ = null;
          resultsSettingsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.Builder getResultsSettingsBuilder() {

        onChanged();
        return getResultsSettingsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettingsOrBuilder getResultsSettingsOrBuilder() {
        if (resultsSettingsBuilder_ != null)
			return resultsSettingsBuilder_.getMessageOrBuilder();
		else
			return resultsSettings_ == null ?
			      uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.getDefaultInstance() : resultsSettings_;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings, uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettings.Builder, uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.ResultsSettingsOrBuilder>
          getResultsSettingsFieldBuilder() {
        if (resultsSettingsBuilder_ == null) {
          resultsSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
                  getResultsSettings(),
                  getParentForChildren(),
                  isClean());
          resultsSettings_ = null;
        }
        return resultsSettingsBuilder_;
      }

      private uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF psf_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF, uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.Builder, uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSFOrBuilder> psfBuilder_;
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      @Override
	public boolean hasPsf() {
        return psfBuilder_ != null || psf_ != null;
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF getPsf() {
        if (psfBuilder_ == null)
			return psf_ == null ? uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.getDefaultInstance() : psf_;
		else
			return psfBuilder_.getMessage();
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      public Builder setPsf(uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF value) {
        if (psfBuilder_ == null) {
          if (value == null)
			throw new NullPointerException();
          psf_ = value;
          onChanged();
        }
		else
			psfBuilder_.setMessage(value);

        return this;
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      public Builder setPsf(
          uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.Builder builderForValue) {
        if (psfBuilder_ == null) {
          psf_ = builderForValue.build();
          onChanged();
        }
		else
			psfBuilder_.setMessage(builderForValue.build());

        return this;
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      public Builder mergePsf(uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF value) {
        if (psfBuilder_ == null) {
          if (psf_ != null)
			psf_ =
              uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.newBuilder(psf_).mergeFrom(value).buildPartial();
		else
			psf_ = value;
          onChanged();
        }
		else
			psfBuilder_.mergeFrom(value);

        return this;
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      public Builder clearPsf() {
        if (psfBuilder_ == null) {
          psf_ = null;
          onChanged();
        } else {
          psf_ = null;
          psfBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      public uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.Builder getPsfBuilder() {

        onChanged();
        return getPsfFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      @Override
	public uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSFOrBuilder getPsfOrBuilder() {
        if (psfBuilder_ != null)
			return psfBuilder_.getMessageOrBuilder();
		else
			return psf_ == null ?
			      uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.getDefaultInstance() : psf_;
      }
      /**
       * <pre>
       * The Point Spread Function (PSF)
       * </pre>
       *
       * <code>.uk.ac.sussex.gdsc.smlm.data.config.PSF psf = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF, uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSF.Builder, uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.PSFOrBuilder>
          getPsfFieldBuilder() {
        if (psfBuilder_ == null) {
          psfBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<>(
                  getPsf(),
                  getParentForChildren(),
                  isClean());
          psf_ = null;
        }
        return psfBuilder_;
      }
      @Override
	public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      @Override
	public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings)
    }

    // @@protoc_insertion_point(class_scope:uk.ac.sussex.gdsc.smlm.data.config.TemplateSettings)
    private static final uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings();
    }

    public static uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TemplateSettings>
        PARSER = new com.google.protobuf.AbstractParser<TemplateSettings>() {
      @Override
	public TemplateSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TemplateSettings(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TemplateSettings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateSettings> getParserForType() {
      return PARSER;
    }

    @Override
	public uk.ac.sussex.gdsc.smlm.data.config.TemplateProtos.TemplateSettings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_descriptor;
  private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    final java.lang.String[] descriptorData = {
      "\n\016template.proto\022\"uk.ac.sussex.gdsc.smlm" +
      ".data.config\032\021calibration.proto\032\tfit.pro" +
      "to\032\rresults.proto\032\tpsf.proto\"\300\002\n\020Templat" +
      "eSettings\022\r\n\005notes\030\001 \003(\t\022D\n\013calibration\030" +
      "\002 \001(\0132/.uk.ac.sussex.gdsc.smlm.data.conf" +
      "ig.Calibration\022R\n\023fit_engine_settings\030\003 " +
      "\001(\01325.uk.ac.sussex.gdsc.smlm.data.config" +
      ".FitEngineSettings\022M\n\020results_settings\030\004" +
      " \001(\01323.uk.ac.sussex.gdsc.smlm.data.confi" +
      "g.ResultsSettings\0224\n\003psf\030\005 \001(\0132\'.uk.ac.s",
      "ussex.gdsc.smlm.data.config.PSFB\020B\016Templ" +
      "ateProtosb\006proto3"
    };
    final com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.getDescriptor(),
          uk.ac.sussex.gdsc.smlm.data.config.FitProtos.getDescriptor(),
          uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.getDescriptor(),
          uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.getDescriptor(),
        }, assigner);
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_uk_ac_sussex_gdsc_smlm_data_config_TemplateSettings_descriptor,
        new java.lang.String[] { "Notes", "Calibration", "FitEngineSettings", "ResultsSettings", "Psf", });
    uk.ac.sussex.gdsc.smlm.data.config.CalibrationProtos.getDescriptor();
    uk.ac.sussex.gdsc.smlm.data.config.FitProtos.getDescriptor();
    uk.ac.sussex.gdsc.smlm.data.config.ResultsProtos.getDescriptor();
    uk.ac.sussex.gdsc.smlm.data.config.PSFProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
