// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: template_config.proto

package gdsc.smlm.data.config;

@SuppressWarnings({"unchecked", "unused"})
public final class TemplateConfig {
  private TemplateConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TemplateSettingsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gdsc.smlm.data.config.TemplateSettings)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    java.util.List<java.lang.String>
        getNotesList();
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    int getNotesCount();
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    java.lang.String getNotes(int index);
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    com.google.protobuf.ByteString
        getNotesBytes(int index);

    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    boolean hasCalibration();
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    gdsc.smlm.data.config.CalibrationConfig.Calibration getCalibration();
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    gdsc.smlm.data.config.CalibrationConfig.CalibrationOrBuilder getCalibrationOrBuilder();

    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    boolean hasFitEngineSettings();
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    gdsc.smlm.data.config.FitConfig.FitEngineSettings getFitEngineSettings();
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    gdsc.smlm.data.config.FitConfig.FitEngineSettingsOrBuilder getFitEngineSettingsOrBuilder();

    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    boolean hasResultsSettings();
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    gdsc.smlm.data.config.ResultsConfig.ResultsSettings getResultsSettings();
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    gdsc.smlm.data.config.ResultsConfig.ResultsSettingsOrBuilder getResultsSettingsOrBuilder();
  }
  /**
   * <pre>
   * Define the settings for the template.
   * </pre>
   *
   * Protobuf type {@code gdsc.smlm.data.config.TemplateSettings}
   */
  public  static final class TemplateSettings extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gdsc.smlm.data.config.TemplateSettings)
      TemplateSettingsOrBuilder {
    // Use TemplateSettings.newBuilder() to construct.
    private TemplateSettings(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TemplateSettings() {
      notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TemplateSettings(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                notes_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              notes_.add(s);
              break;
            }
            case 18: {
              gdsc.smlm.data.config.CalibrationConfig.Calibration.Builder subBuilder = null;
              if (calibration_ != null) {
                subBuilder = calibration_.toBuilder();
              }
              calibration_ = input.readMessage(gdsc.smlm.data.config.CalibrationConfig.Calibration.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(calibration_);
                calibration_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              gdsc.smlm.data.config.FitConfig.FitEngineSettings.Builder subBuilder = null;
              if (fitEngineSettings_ != null) {
                subBuilder = fitEngineSettings_.toBuilder();
              }
              fitEngineSettings_ = input.readMessage(gdsc.smlm.data.config.FitConfig.FitEngineSettings.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(fitEngineSettings_);
                fitEngineSettings_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              gdsc.smlm.data.config.ResultsConfig.ResultsSettings.Builder subBuilder = null;
              if (resultsSettings_ != null) {
                subBuilder = resultsSettings_.toBuilder();
              }
              resultsSettings_ = input.readMessage(gdsc.smlm.data.config.ResultsConfig.ResultsSettings.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultsSettings_);
                resultsSettings_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = notes_.getUnmodifiableView();
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gdsc.smlm.data.config.TemplateConfig.internal_static_gdsc_smlm_data_config_TemplateSettings_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gdsc.smlm.data.config.TemplateConfig.internal_static_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gdsc.smlm.data.config.TemplateConfig.TemplateSettings.class, gdsc.smlm.data.config.TemplateConfig.TemplateSettings.Builder.class);
    }

    private int bitField0_;
    public static final int NOTES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList notes_;
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNotesList() {
      return notes_;
    }
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    public int getNotesCount() {
      return notes_.size();
    }
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    public java.lang.String getNotes(int index) {
      return notes_.get(index);
    }
    /**
     * <pre>
     * Any notes describing the template
     * </pre>
     *
     * <code>repeated string notes = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNotesBytes(int index) {
      return notes_.getByteString(index);
    }

    public static final int CALIBRATION_FIELD_NUMBER = 2;
    private gdsc.smlm.data.config.CalibrationConfig.Calibration calibration_;
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    public boolean hasCalibration() {
      return calibration_ != null;
    }
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    public gdsc.smlm.data.config.CalibrationConfig.Calibration getCalibration() {
      return calibration_ == null ? gdsc.smlm.data.config.CalibrationConfig.Calibration.getDefaultInstance() : calibration_;
    }
    /**
     * <pre>
     * The calibration
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
     */
    public gdsc.smlm.data.config.CalibrationConfig.CalibrationOrBuilder getCalibrationOrBuilder() {
      return getCalibration();
    }

    public static final int FIT_ENGINE_SETTINGS_FIELD_NUMBER = 3;
    private gdsc.smlm.data.config.FitConfig.FitEngineSettings fitEngineSettings_;
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    public boolean hasFitEngineSettings() {
      return fitEngineSettings_ != null;
    }
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    public gdsc.smlm.data.config.FitConfig.FitEngineSettings getFitEngineSettings() {
      return fitEngineSettings_ == null ? gdsc.smlm.data.config.FitConfig.FitEngineSettings.getDefaultInstance() : fitEngineSettings_;
    }
    /**
     * <pre>
     * The fit engine settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
     */
    public gdsc.smlm.data.config.FitConfig.FitEngineSettingsOrBuilder getFitEngineSettingsOrBuilder() {
      return getFitEngineSettings();
    }

    public static final int RESULTS_SETTINGS_FIELD_NUMBER = 4;
    private gdsc.smlm.data.config.ResultsConfig.ResultsSettings resultsSettings_;
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    public boolean hasResultsSettings() {
      return resultsSettings_ != null;
    }
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    public gdsc.smlm.data.config.ResultsConfig.ResultsSettings getResultsSettings() {
      return resultsSettings_ == null ? gdsc.smlm.data.config.ResultsConfig.ResultsSettings.getDefaultInstance() : resultsSettings_;
    }
    /**
     * <pre>
     * The results settings
     * </pre>
     *
     * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
     */
    public gdsc.smlm.data.config.ResultsConfig.ResultsSettingsOrBuilder getResultsSettingsOrBuilder() {
      return getResultsSettings();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < notes_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, notes_.getRaw(i));
      }
      if (calibration_ != null) {
        output.writeMessage(2, getCalibration());
      }
      if (fitEngineSettings_ != null) {
        output.writeMessage(3, getFitEngineSettings());
      }
      if (resultsSettings_ != null) {
        output.writeMessage(4, getResultsSettings());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < notes_.size(); i++) {
          dataSize += computeStringSizeNoTag(notes_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getNotesList().size();
      }
      if (calibration_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCalibration());
      }
      if (fitEngineSettings_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getFitEngineSettings());
      }
      if (resultsSettings_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getResultsSettings());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof gdsc.smlm.data.config.TemplateConfig.TemplateSettings)) {
        return super.equals(obj);
      }
      gdsc.smlm.data.config.TemplateConfig.TemplateSettings other = (gdsc.smlm.data.config.TemplateConfig.TemplateSettings) obj;

      boolean result = true;
      result = result && getNotesList()
          .equals(other.getNotesList());
      result = result && (hasCalibration() == other.hasCalibration());
      if (hasCalibration()) {
        result = result && getCalibration()
            .equals(other.getCalibration());
      }
      result = result && (hasFitEngineSettings() == other.hasFitEngineSettings());
      if (hasFitEngineSettings()) {
        result = result && getFitEngineSettings()
            .equals(other.getFitEngineSettings());
      }
      result = result && (hasResultsSettings() == other.hasResultsSettings());
      if (hasResultsSettings()) {
        result = result && getResultsSettings()
            .equals(other.getResultsSettings());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getNotesCount() > 0) {
        hash = (37 * hash) + NOTES_FIELD_NUMBER;
        hash = (53 * hash) + getNotesList().hashCode();
      }
      if (hasCalibration()) {
        hash = (37 * hash) + CALIBRATION_FIELD_NUMBER;
        hash = (53 * hash) + getCalibration().hashCode();
      }
      if (hasFitEngineSettings()) {
        hash = (37 * hash) + FIT_ENGINE_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getFitEngineSettings().hashCode();
      }
      if (hasResultsSettings()) {
        hash = (37 * hash) + RESULTS_SETTINGS_FIELD_NUMBER;
        hash = (53 * hash) + getResultsSettings().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(gdsc.smlm.data.config.TemplateConfig.TemplateSettings prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Define the settings for the template.
     * </pre>
     *
     * Protobuf type {@code gdsc.smlm.data.config.TemplateSettings}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gdsc.smlm.data.config.TemplateSettings)
        gdsc.smlm.data.config.TemplateConfig.TemplateSettingsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gdsc.smlm.data.config.TemplateConfig.internal_static_gdsc_smlm_data_config_TemplateSettings_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gdsc.smlm.data.config.TemplateConfig.internal_static_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gdsc.smlm.data.config.TemplateConfig.TemplateSettings.class, gdsc.smlm.data.config.TemplateConfig.TemplateSettings.Builder.class);
      }

      // Construct using gdsc.smlm.data.config.TemplateConfig.TemplateSettings.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (calibrationBuilder_ == null) {
          calibration_ = null;
        } else {
          calibration_ = null;
          calibrationBuilder_ = null;
        }
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettings_ = null;
        } else {
          fitEngineSettings_ = null;
          fitEngineSettingsBuilder_ = null;
        }
        if (resultsSettingsBuilder_ == null) {
          resultsSettings_ = null;
        } else {
          resultsSettings_ = null;
          resultsSettingsBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gdsc.smlm.data.config.TemplateConfig.internal_static_gdsc_smlm_data_config_TemplateSettings_descriptor;
      }

      public gdsc.smlm.data.config.TemplateConfig.TemplateSettings getDefaultInstanceForType() {
        return gdsc.smlm.data.config.TemplateConfig.TemplateSettings.getDefaultInstance();
      }

      public gdsc.smlm.data.config.TemplateConfig.TemplateSettings build() {
        gdsc.smlm.data.config.TemplateConfig.TemplateSettings result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gdsc.smlm.data.config.TemplateConfig.TemplateSettings buildPartial() {
        gdsc.smlm.data.config.TemplateConfig.TemplateSettings result = new gdsc.smlm.data.config.TemplateConfig.TemplateSettings(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = notes_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.notes_ = notes_;
        if (calibrationBuilder_ == null) {
          result.calibration_ = calibration_;
        } else {
          result.calibration_ = calibrationBuilder_.build();
        }
        if (fitEngineSettingsBuilder_ == null) {
          result.fitEngineSettings_ = fitEngineSettings_;
        } else {
          result.fitEngineSettings_ = fitEngineSettingsBuilder_.build();
        }
        if (resultsSettingsBuilder_ == null) {
          result.resultsSettings_ = resultsSettings_;
        } else {
          result.resultsSettings_ = resultsSettingsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gdsc.smlm.data.config.TemplateConfig.TemplateSettings) {
          return mergeFrom((gdsc.smlm.data.config.TemplateConfig.TemplateSettings)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gdsc.smlm.data.config.TemplateConfig.TemplateSettings other) {
        if (other == gdsc.smlm.data.config.TemplateConfig.TemplateSettings.getDefaultInstance()) return this;
        if (!other.notes_.isEmpty()) {
          if (notes_.isEmpty()) {
            notes_ = other.notes_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNotesIsMutable();
            notes_.addAll(other.notes_);
          }
          onChanged();
        }
        if (other.hasCalibration()) {
          mergeCalibration(other.getCalibration());
        }
        if (other.hasFitEngineSettings()) {
          mergeFitEngineSettings(other.getFitEngineSettings());
        }
        if (other.hasResultsSettings()) {
          mergeResultsSettings(other.getResultsSettings());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gdsc.smlm.data.config.TemplateConfig.TemplateSettings parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gdsc.smlm.data.config.TemplateConfig.TemplateSettings) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureNotesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          notes_ = new com.google.protobuf.LazyStringArrayList(notes_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getNotesList() {
        return notes_.getUnmodifiableView();
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public int getNotesCount() {
        return notes_.size();
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public java.lang.String getNotes(int index) {
        return notes_.get(index);
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNotesBytes(int index) {
        return notes_.getByteString(index);
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder setNotes(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNotesIsMutable();
        notes_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder addNotes(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureNotesIsMutable();
        notes_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder addAllNotes(
          java.lang.Iterable<java.lang.String> values) {
        ensureNotesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, notes_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder clearNotes() {
        notes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Any notes describing the template
       * </pre>
       *
       * <code>repeated string notes = 1;</code>
       */
      public Builder addNotesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureNotesIsMutable();
        notes_.add(value);
        onChanged();
        return this;
      }

      private gdsc.smlm.data.config.CalibrationConfig.Calibration calibration_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          gdsc.smlm.data.config.CalibrationConfig.Calibration, gdsc.smlm.data.config.CalibrationConfig.Calibration.Builder, gdsc.smlm.data.config.CalibrationConfig.CalibrationOrBuilder> calibrationBuilder_;
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public boolean hasCalibration() {
        return calibrationBuilder_ != null || calibration_ != null;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public gdsc.smlm.data.config.CalibrationConfig.Calibration getCalibration() {
        if (calibrationBuilder_ == null) {
          return calibration_ == null ? gdsc.smlm.data.config.CalibrationConfig.Calibration.getDefaultInstance() : calibration_;
        } else {
          return calibrationBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder setCalibration(gdsc.smlm.data.config.CalibrationConfig.Calibration value) {
        if (calibrationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          calibration_ = value;
          onChanged();
        } else {
          calibrationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder setCalibration(
          gdsc.smlm.data.config.CalibrationConfig.Calibration.Builder builderForValue) {
        if (calibrationBuilder_ == null) {
          calibration_ = builderForValue.build();
          onChanged();
        } else {
          calibrationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder mergeCalibration(gdsc.smlm.data.config.CalibrationConfig.Calibration value) {
        if (calibrationBuilder_ == null) {
          if (calibration_ != null) {
            calibration_ =
              gdsc.smlm.data.config.CalibrationConfig.Calibration.newBuilder(calibration_).mergeFrom(value).buildPartial();
          } else {
            calibration_ = value;
          }
          onChanged();
        } else {
          calibrationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public Builder clearCalibration() {
        if (calibrationBuilder_ == null) {
          calibration_ = null;
          onChanged();
        } else {
          calibration_ = null;
          calibrationBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public gdsc.smlm.data.config.CalibrationConfig.Calibration.Builder getCalibrationBuilder() {
        
        onChanged();
        return getCalibrationFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      public gdsc.smlm.data.config.CalibrationConfig.CalibrationOrBuilder getCalibrationOrBuilder() {
        if (calibrationBuilder_ != null) {
          return calibrationBuilder_.getMessageOrBuilder();
        } else {
          return calibration_ == null ?
              gdsc.smlm.data.config.CalibrationConfig.Calibration.getDefaultInstance() : calibration_;
        }
      }
      /**
       * <pre>
       * The calibration
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.Calibration calibration = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gdsc.smlm.data.config.CalibrationConfig.Calibration, gdsc.smlm.data.config.CalibrationConfig.Calibration.Builder, gdsc.smlm.data.config.CalibrationConfig.CalibrationOrBuilder> 
          getCalibrationFieldBuilder() {
        if (calibrationBuilder_ == null) {
          calibrationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gdsc.smlm.data.config.CalibrationConfig.Calibration, gdsc.smlm.data.config.CalibrationConfig.Calibration.Builder, gdsc.smlm.data.config.CalibrationConfig.CalibrationOrBuilder>(
                  getCalibration(),
                  getParentForChildren(),
                  isClean());
          calibration_ = null;
        }
        return calibrationBuilder_;
      }

      private gdsc.smlm.data.config.FitConfig.FitEngineSettings fitEngineSettings_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          gdsc.smlm.data.config.FitConfig.FitEngineSettings, gdsc.smlm.data.config.FitConfig.FitEngineSettings.Builder, gdsc.smlm.data.config.FitConfig.FitEngineSettingsOrBuilder> fitEngineSettingsBuilder_;
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public boolean hasFitEngineSettings() {
        return fitEngineSettingsBuilder_ != null || fitEngineSettings_ != null;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public gdsc.smlm.data.config.FitConfig.FitEngineSettings getFitEngineSettings() {
        if (fitEngineSettingsBuilder_ == null) {
          return fitEngineSettings_ == null ? gdsc.smlm.data.config.FitConfig.FitEngineSettings.getDefaultInstance() : fitEngineSettings_;
        } else {
          return fitEngineSettingsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder setFitEngineSettings(gdsc.smlm.data.config.FitConfig.FitEngineSettings value) {
        if (fitEngineSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          fitEngineSettings_ = value;
          onChanged();
        } else {
          fitEngineSettingsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder setFitEngineSettings(
          gdsc.smlm.data.config.FitConfig.FitEngineSettings.Builder builderForValue) {
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettings_ = builderForValue.build();
          onChanged();
        } else {
          fitEngineSettingsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder mergeFitEngineSettings(gdsc.smlm.data.config.FitConfig.FitEngineSettings value) {
        if (fitEngineSettingsBuilder_ == null) {
          if (fitEngineSettings_ != null) {
            fitEngineSettings_ =
              gdsc.smlm.data.config.FitConfig.FitEngineSettings.newBuilder(fitEngineSettings_).mergeFrom(value).buildPartial();
          } else {
            fitEngineSettings_ = value;
          }
          onChanged();
        } else {
          fitEngineSettingsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public Builder clearFitEngineSettings() {
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettings_ = null;
          onChanged();
        } else {
          fitEngineSettings_ = null;
          fitEngineSettingsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public gdsc.smlm.data.config.FitConfig.FitEngineSettings.Builder getFitEngineSettingsBuilder() {
        
        onChanged();
        return getFitEngineSettingsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      public gdsc.smlm.data.config.FitConfig.FitEngineSettingsOrBuilder getFitEngineSettingsOrBuilder() {
        if (fitEngineSettingsBuilder_ != null) {
          return fitEngineSettingsBuilder_.getMessageOrBuilder();
        } else {
          return fitEngineSettings_ == null ?
              gdsc.smlm.data.config.FitConfig.FitEngineSettings.getDefaultInstance() : fitEngineSettings_;
        }
      }
      /**
       * <pre>
       * The fit engine settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.FitEngineSettings fit_engine_settings = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gdsc.smlm.data.config.FitConfig.FitEngineSettings, gdsc.smlm.data.config.FitConfig.FitEngineSettings.Builder, gdsc.smlm.data.config.FitConfig.FitEngineSettingsOrBuilder> 
          getFitEngineSettingsFieldBuilder() {
        if (fitEngineSettingsBuilder_ == null) {
          fitEngineSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gdsc.smlm.data.config.FitConfig.FitEngineSettings, gdsc.smlm.data.config.FitConfig.FitEngineSettings.Builder, gdsc.smlm.data.config.FitConfig.FitEngineSettingsOrBuilder>(
                  getFitEngineSettings(),
                  getParentForChildren(),
                  isClean());
          fitEngineSettings_ = null;
        }
        return fitEngineSettingsBuilder_;
      }

      private gdsc.smlm.data.config.ResultsConfig.ResultsSettings resultsSettings_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          gdsc.smlm.data.config.ResultsConfig.ResultsSettings, gdsc.smlm.data.config.ResultsConfig.ResultsSettings.Builder, gdsc.smlm.data.config.ResultsConfig.ResultsSettingsOrBuilder> resultsSettingsBuilder_;
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public boolean hasResultsSettings() {
        return resultsSettingsBuilder_ != null || resultsSettings_ != null;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public gdsc.smlm.data.config.ResultsConfig.ResultsSettings getResultsSettings() {
        if (resultsSettingsBuilder_ == null) {
          return resultsSettings_ == null ? gdsc.smlm.data.config.ResultsConfig.ResultsSettings.getDefaultInstance() : resultsSettings_;
        } else {
          return resultsSettingsBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder setResultsSettings(gdsc.smlm.data.config.ResultsConfig.ResultsSettings value) {
        if (resultsSettingsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resultsSettings_ = value;
          onChanged();
        } else {
          resultsSettingsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder setResultsSettings(
          gdsc.smlm.data.config.ResultsConfig.ResultsSettings.Builder builderForValue) {
        if (resultsSettingsBuilder_ == null) {
          resultsSettings_ = builderForValue.build();
          onChanged();
        } else {
          resultsSettingsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder mergeResultsSettings(gdsc.smlm.data.config.ResultsConfig.ResultsSettings value) {
        if (resultsSettingsBuilder_ == null) {
          if (resultsSettings_ != null) {
            resultsSettings_ =
              gdsc.smlm.data.config.ResultsConfig.ResultsSettings.newBuilder(resultsSettings_).mergeFrom(value).buildPartial();
          } else {
            resultsSettings_ = value;
          }
          onChanged();
        } else {
          resultsSettingsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public Builder clearResultsSettings() {
        if (resultsSettingsBuilder_ == null) {
          resultsSettings_ = null;
          onChanged();
        } else {
          resultsSettings_ = null;
          resultsSettingsBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public gdsc.smlm.data.config.ResultsConfig.ResultsSettings.Builder getResultsSettingsBuilder() {
        
        onChanged();
        return getResultsSettingsFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      public gdsc.smlm.data.config.ResultsConfig.ResultsSettingsOrBuilder getResultsSettingsOrBuilder() {
        if (resultsSettingsBuilder_ != null) {
          return resultsSettingsBuilder_.getMessageOrBuilder();
        } else {
          return resultsSettings_ == null ?
              gdsc.smlm.data.config.ResultsConfig.ResultsSettings.getDefaultInstance() : resultsSettings_;
        }
      }
      /**
       * <pre>
       * The results settings
       * </pre>
       *
       * <code>.gdsc.smlm.data.config.ResultsSettings results_settings = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          gdsc.smlm.data.config.ResultsConfig.ResultsSettings, gdsc.smlm.data.config.ResultsConfig.ResultsSettings.Builder, gdsc.smlm.data.config.ResultsConfig.ResultsSettingsOrBuilder> 
          getResultsSettingsFieldBuilder() {
        if (resultsSettingsBuilder_ == null) {
          resultsSettingsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              gdsc.smlm.data.config.ResultsConfig.ResultsSettings, gdsc.smlm.data.config.ResultsConfig.ResultsSettings.Builder, gdsc.smlm.data.config.ResultsConfig.ResultsSettingsOrBuilder>(
                  getResultsSettings(),
                  getParentForChildren(),
                  isClean());
          resultsSettings_ = null;
        }
        return resultsSettingsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gdsc.smlm.data.config.TemplateSettings)
    }

    // @@protoc_insertion_point(class_scope:gdsc.smlm.data.config.TemplateSettings)
    private static final gdsc.smlm.data.config.TemplateConfig.TemplateSettings DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new gdsc.smlm.data.config.TemplateConfig.TemplateSettings();
    }

    public static gdsc.smlm.data.config.TemplateConfig.TemplateSettings getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TemplateSettings>
        PARSER = new com.google.protobuf.AbstractParser<TemplateSettings>() {
      public TemplateSettings parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new TemplateSettings(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TemplateSettings> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateSettings> getParserForType() {
      return PARSER;
    }

    public gdsc.smlm.data.config.TemplateConfig.TemplateSettings getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gdsc_smlm_data_config_TemplateSettings_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025template_config.proto\022\025gdsc.smlm.data." +
      "config\032\030calibration_config.proto\032\020fit_co" +
      "nfig.proto\032\024results_config.proto\"\343\001\n\020Tem" +
      "plateSettings\022\r\n\005notes\030\001 \003(\t\0227\n\013calibrat" +
      "ion\030\002 \001(\0132\".gdsc.smlm.data.config.Calibr" +
      "ation\022E\n\023fit_engine_settings\030\003 \001(\0132(.gds" +
      "c.smlm.data.config.FitEngineSettings\022@\n\020" +
      "results_settings\030\004 \001(\0132&.gdsc.smlm.data." +
      "config.ResultsSettingsB\020B\016TemplateConfig" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gdsc.smlm.data.config.CalibrationConfig.getDescriptor(),
          gdsc.smlm.data.config.FitConfig.getDescriptor(),
          gdsc.smlm.data.config.ResultsConfig.getDescriptor(),
        }, assigner);
    internal_static_gdsc_smlm_data_config_TemplateSettings_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gdsc_smlm_data_config_TemplateSettings_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gdsc_smlm_data_config_TemplateSettings_descriptor,
        new java.lang.String[] { "Notes", "Calibration", "FitEngineSettings", "ResultsSettings", });
    gdsc.smlm.data.config.CalibrationConfig.getDescriptor();
    gdsc.smlm.data.config.FitConfig.getDescriptor();
    gdsc.smlm.data.config.ResultsConfig.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
