name: Java CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8 ]

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: 'maven'
    - name: Purge maven snapshots
      run: mvn -B --no-transfer-progress dependency:purge-local-repository -DmanualInclude="uk.ac.sussex.gdsc:gdsc-ij-parent,uk.ac.sussex.gdsc:gdsc-smlm,uk.ac.sussex.gdsc:gdsc-smlm-ij"
    - name: Build
      # Note: revapi is skipped only in the modules containing the profile
      run: mvn -V -B --no-transfer-progress -P jacoco,revapi-skip checkstyle:check verify jacoco:report
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        files: ./gdsc-smlm/target/site/jacoco/jacoco.xml,./gdsc-smlm-ij/target/site/jacoco/jacoco.xml
